#!/bin/bash

npm version ${1:-minor}

version=$(awk -F \" '/"version": ".+"/ { print $4; exit; }' package.json)

dir=release/treefrog-$version

mkdir -p $dir

mkdir $dir/build

cp -R build/electron $dir/build/
cp -R src $dir/
cp -R vendor $dir/
cp package* $dir/
cp licenses $dir/
